# Site settings
title:          "Street Daily Wrap"
description:    "one-stop reviewing the market performance everyday"
baseurl:        ""
url:            "https://jayonmobile.github.io/"

# Google Analytics
google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         "Street Daily Wrap"
  url:          "https://jayonmobile.github.io/"
  email:        "contact@streetdailywrap.com"

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-stickyposts
  - jemoji
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
disqus:         jekyll-tale
#theme: jekyll-theme-minimal

# Emoji
emoji:
  src: "https://github.githubassets.com/images/icons/"